export enum TooltipMessages {
  seeAPIKey = 'seeAPIKey',
  deleteAPIKey = 'deleteAPIKey',
  revealAPIKey = 'revealAPIKey',
  enableAPIKey = 'enableAPIKey',
  disableAPIKey = 'disableAPIKey',
  editModalTitle = 'editModalTitle',
  refreshService = 'refreshService',
  removeService = 'removeService',
  seeProject = 'seeProject',
  deleteProject = 'deleteProject',
  seeClient = 'seeClient',
  deleteClient = 'deleteClient',
  deleteService = 'deleteService',
  seeEnvironment = 'seeEnvironment',
  deleteEnvironment = 'deleteEnvironment',
}

export const TooltipMessagesLabels: Record<TooltipMessages, string> = {
  [TooltipMessages.seeAPIKey]: 'See API key.',
  [TooltipMessages.deleteAPIKey]: 'Delete API key.',
  [TooltipMessages.revealAPIKey]: 'Reveal API key.',
  [TooltipMessages.enableAPIKey]: 'Enable API key',
  [TooltipMessages.disableAPIKey]: 'Disable API key',
  [TooltipMessages.editModalTitle]: 'Edit',
  [TooltipMessages.refreshService]: 'Refresh available requests.',
  [TooltipMessages.removeService]: 'Remove service.',
  [TooltipMessages.seeProject]: 'See project.',
  [TooltipMessages.deleteProject]: 'Delete project.',
  [TooltipMessages.seeClient]: 'See client.',
  [TooltipMessages.deleteClient]: 'Delete client.',
  [TooltipMessages.deleteService]: 'Delete service.',
  [TooltipMessages.seeEnvironment]: 'See environment.',
  [TooltipMessages.deleteEnvironment]: 'Delete environment',
};
