import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowsRotate,
  faBars,
  faChartSimple,
  faClipboard,
  faCodeBranch,
  faCubes,
  faDiagramProject,
  faEye,
  faEyeSlash,
  faFile,
  faHouse,
  faKey,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMoon,
  faPenToSquare,
  faPlus,
  faQuestion,
  faRightFromBracket,
  faServer,
  faSignOutAlt,
  faSun,
  faTrashCan,
  faUser,
  faUserGroup,
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

library.add(
  faArrowsRotate,
  faBars,
  faChartSimple,
  faClipboard,
  faCodeBranch,
  faCubes,
  faDiagramProject,
  faEye,
  faEyeSlash,
  faFile,
  faHouse,
  faKey,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMoon,
  faPenToSquare,
  faPlus,
  faQuestion,
  faRightFromBracket,
  faServer,
  faSignOutAlt,
  faSun,
  faTrashCan,
  faUser,
  faUserGroup,
);

export default FontAwesomeIcon;
